### ISSUE TITLE
`rake californica:ingest:clean` fails with timeout in production

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#238]
```rake aborted!
Faraday::TimeoutError: Net::ReadTimeout
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-encoding-0.0.4/lib/faraday/encoding.rb:12:in `call'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `delete'
/opt/californica/shared/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:63:in `block in delete'
/opt/californica/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
/opt/californica/shared/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:61:in `delete'
/opt/californica/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/initializing_connection.rb:32:in `delete'
/opt/californica/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/cleaner.rb:17:in `delete_root_resource'
/opt/californica/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/cleaner.rb:10:in `cleanout_fedora'
/opt/californica/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/cleaner.rb:4:in `clean!'
/opt/californica/releases/20180928162223/lib/tasks/ingest.rake:24:in `block (4 levels) in <top (required)>'
/opt/californica/shared/bundle/ruby/2.5.0/gems/retries-0.0.5/lib/retries.rb:46:in `with_retries'
/opt/californica/releases/20180928162223/lib/tasks/ingest.rake:23:in `block (3 levels) in <top (required)>'
/opt/californica/releases/20180928162223/lib/tasks/ingest.rake:34:in `block (3 levels) in <top (required)>'
/opt/californica/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/bin/bundle:30:in `block in <main>'
/usr/bin/bundle:22:in `<main>'

Caused by:
Net::ReadTimeout: Net::ReadTimeout
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-encoding-0.0.4/lib/faraday/encoding.rb:12:in `call'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
/opt/californica/shared/bundle/ruby/2.5.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `delete'
/opt/californica/shared/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:63:in `block in delete'
/opt/californica/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
/opt/californica/shared/bundle/ruby/2.5.0/gems/ldp-0.7.2/lib/ldp/client/methods.rb:61:in `delete'
/opt/californica/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/initializing_connection.rb:32:in `delete'
/opt/californica/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/cleaner.rb:17:in `delete_root_resource'
/opt/californica/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/cleaner.rb:10:in `cleanout_fedora'
/opt/californica/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/cleaner.rb:4:in `clean!'
/opt/californica/releases/20180928162223/lib/tasks/ingest.rake:24:in `block (4 levels) in <top (required)>'
/opt/californica/shared/bundle/ruby/2.5.0/gems/retries-0.0.5/lib/retries.rb:46:in `with_retries'
/opt/californica/releases/20180928162223/lib/tasks/ingest.rake:23:in `block (3 levels) in <top (required)>'
/opt/californica/releases/20180928162223/lib/tasks/ingest.rake:34:in `block (3 levels) in <top (required)>'
/opt/californica/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/bin/bundle:30:in `block in <main>'
/usr/bin/bundle:22:in `<main>'
Tasks: TOP => californica:ingest:clean```

**Comment by no-reply** [comment]
This might be (partially?) addressed by https://github.com/UCLALibrary/californica/pull/237.

**Comment by emcaulay** [comment]
Related to #237.

**Comment by hardyoyo** [comment]
so... Fedora is timing out during this process. Timeouts sometimes happen when a script is just "in too much of a hurry," and one approach is to adjust the timeout to be "more patient". Timeouts also sometimes occur when a server becomes unavailable for some reason. I'm wondering if Fedora is crashing during this process? We should look at the fedora logs.

**Comment by val99erie** [comment]
I have heard that there is a known issue with `ActiveFedora::Cleaner` using a cleaning strategy that starts from the root node, and that it causes problems for repos that have more than a few thousand records.  This is second-hand knowledge, so I'll try to find some more concrete information next week.  If that turns out to be the problem, we might try a cleaning strategy that loops through records, or one that deletes lower nodes before coming up to the root.

**Comment by emcaulay** [comment]
Ah, insider knowledge! Very cool. Thank you @val99erie !

**Comment by bess** [comment]
After discussion with Mark we decided we've already spent too much time on this problem. We aren't going to want to blow away a huge production database automatically ever, so let's not spend more time on this. Instead, let's figure out how to do incremental updates when the metadata changes.
