### ISSUE TITLE
ensure team members can deploy to the UCLA RHEL-based infrastructure

### ISSUE THREAD

**Issue by hardyoyo** [UCLALibrary/californica#68]
As soon as #67 is complete, and the infrastructure is ready, we should ensure that all team members can deploy to this infrastructure (similar to #17). 

## ACCEPTANCE
Each of the following folks can deploy
- [x] Stephen
- [x] Hardy
- [x] Kristian
- [x] Darrow
- [x] Kevin
- [x] Bess
- [x] Tom
- [x] Mark B.
- [x] Valerie - might be issues here with respect to ssh key being used
- [x] Jamie
- [x] AndyW
- [x] JenD

**Comment by sgurnick** [comment]
Accounts and SSH public keys installed on `jump.library.ucla.edu` for the following users:

- [X] Stephen
- [X] Hardy
- [X] Kristian
- [X] Darrow
- [X] Kevin
- [X] Bess
- [X] Tom
- [X] Mark B.

Does Andrew Wallace still need deployment access?

**Comment by sgurnick** [comment]
Run this command to test deployment to the UCLA test server:
`VIA_JUMP=yes BRANCH=master bundle exec cap californica-test deploy`

**Comment by bess** [comment]
Sadly, I cannot deploy. 
```
bess@lorca:~/projects/californica$ VIA_JUMP=yes BRANCH=master bundle exec cap californica-test deploy                                                            
00:00 git:wrapper                                                                                                                                                
      01 mkdir -p /tmp                                                                                                                                           
#<Thread:0x0000561545138408@/home/bess/.rvm/gems/ruby-2.5.1@californica/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (repo
rt_on_exception is true):                                                                                                                                        
Traceback (most recent call last):                                                                                                                               
        1: from /home/bess/.rvm/gems/ruby-2.5.1@californica/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'                
/home/bess/.rvm/gems/ruby-2.5.1@californica/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while exec
uting as deploy@californica-test.library.ucla.edu: command timed out: ssh -p 31926 bess@jump.library.ucla.edu -W californica-test.library.ucla.edu:22 (SSHKit::Ru
nner::ExecuteError)                                                                                                                                              
(Backtrace restricted to imported tasks)                                                                                                                         
cap aborted!                                                                                                                                                     
SSHKit::Runner::ExecuteError: Exception while executing as deploy@californica-test.library.ucla.edu: command timed out: ssh -p 31926 bess@jump.library.ucla.edu -
W californica-test.library.ucla.edu:22                                                                                                                           
                                                                                                                                                                 
                                                                                                                                                                 
Caused by:                                                                                                                                                       
Net::SSH::Proxy::ConnectError: command timed out: ssh -p 31926 bess@jump.library.ucla.edu -W californica-test.library.ucla.edu:22                                
                                                                                                                                                                 

Caused by:
command timed out

```

**Comment by sgurnick** [comment]
@ksclarke : yes that is one option for setting the username when running a deploy if you know your local username does not match what you have on the jump server.

The other issue you will most likely encounter is the account you are coming from within your vagrant environment does not have your ssh public keys installed that match what you have in your `authorized_keys` file on the jumper server (unless you explicitly put them there ahead of time).
